server:
  port: 8081
spring:
  application:
    name: hospital-medical-record-management-system-serverx

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.116.226.x:3306/hospital?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: "@Abc123456x"
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.hospital.*.domain

